#ifndef _EXTRAS_FONTS_CONFIG_H_
#define _EXTRAS_FONTS_CONFIG_H_

#ifndef FONTS_GLCD_5X7
#define FONTS_GLCD_5X7 1
#endif

// FIXME: Proportional fonts drawing is broken
#ifndef FONTS_ROBOTO_8PT
#define FONTS_ROBOTO_8PT 0
#endif

#ifndef FONTS_ROBOTO_10PT
#define FONTS_ROBOTO_10PT 0
#endif

#ifndef FONTS_BITOCRA_4X7
#define FONTS_BITOCRA_4X7 1
#endif

#ifndef FONTS_BITOCRA_6X11
#define FONTS_BITOCRA_6X11 1
#endif

#ifndef FONTS_BITOCRA_7X13
#define FONTS_BITOCRA_7X13 1
#endif

#ifndef FONTS_TERMINUS_6X12_KOI8_R
#define FONTS_TERMINUS_6X12_KOI8_R 1
#endif

#ifndef FONTS_TERMINUS_8X14_KOI8_R
#define FONTS_TERMINUS_8X14_KOI8_R 1
#endif

#ifndef FONTS_TERMINUS_BOLD_8X14_KOI8_R
#define FONTS_TERMINUS_BOLD_8X14_KOI8_R 1
#endif

#ifndef FONTS_TERMINUS_14X28_KOI8_R
#define FONTS_TERMINUS_14X28_KOI8_R 1
#endif

#ifndef FONTS_TERMINUS_BOLD_14X28_KOI8_R
#define FONTS_TERMINUS_BOLD_14X28_KOI8_R 1
#endif

#ifndef FONTS_TERMINUS_16X32_KOI8_R
#define FONTS_TERMINUS_16X32_KOI8_R 1
#endif

#ifndef FONTS_TERMINUS_BOLD_16X32_KOI8_R
#define FONTS_TERMINUS_BOLD_16X32_KOI8_R 1
#endif

#endif /* _EXTRAS_FONTS_CONFIG_H_ */
